server:
  port: 8080


spring:
  profiles:
    active: local
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view

  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: com.etoak.crawl.model

log:
  path:

---
spring:
  profiles: local
  datasource:
    #url: jdbc:mysql://rm-bp14opizs59270391.mysql.rds.aliyuncs.com:3306/sdcrm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/sdcrm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    db-name: sdcrm #用来搜集数据库的所有表
    filters: wall,mergeStat



  spring:
    redis:
      host: 192.168.1.93
      password:
      port: 6379
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1